import { Link } from 'react-router-dom'

export default function Privacy() {
  return (
    <div className="min-h-screen bg-[var(--bg)]">
      <nav className="px-8 py-4 flex items-center gap-2.5 border-b border-[var(--border)]">
        <Link to="/" className="flex items-center gap-2.5 no-underline">
          <svg width="28" height="28" viewBox="0 0 512 512">
            <circle cx="256" cy="256" r="22" fill="#8B5CF6" opacity="0.85"/>
            <circle cx="256" cy="256" r="10" fill="#fff" opacity="0.95"/>
          </svg>
          <span className="font-extrabold text-[var(--text)] text-lg tracking-tight">Lodestone</span>
        </Link>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-extrabold mb-2 tracking-tight">Privacy Policy</h1>
        <p className="text-sm text-[var(--text-dim)] mb-10">Last updated: June 2026</p>

        <div className="space-y-8 text-[var(--text-muted)] leading-relaxed text-[15px]">
          <section>
            <p>Greyrock Studio ("Company," "we," "us") operates Lodestone, a desktop and web-based AI agent platform. This Privacy Policy explains how we collect, use, store, and protect your information, in compliance with the Personal Information Protection and Electronic Documents Act (PIPEDA) and applicable Canadian privacy law.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">1. Information We Collect</h2>

            <h3 className="font-semibold text-[var(--text)] mb-2">a) Information You Provide</h3>
            <ul className="list-disc pl-6 space-y-1 mb-4">
              <li><strong className="text-[var(--text)]">Account information:</strong> Email address, display name, and password (hashed)</li>
              <li><strong className="text-[var(--text)]">Payment information:</strong> Processed by Stripe; we store only a tokenized reference, not card details</li>
              <li><strong className="text-[var(--text)]">API keys:</strong> When you configure third-party AI providers, your API keys are stored locally on your device and never transmitted to our servers</li>
              <li><strong className="text-[var(--text)]">Customization data:</strong> Agent names, personalities, and preferences you configure</li>
            </ul>

            <h3 className="font-semibold text-[var(--text)] mb-2">b) Information Generated by Use</h3>
            <ul className="list-disc pl-6 space-y-1 mb-4">
              <li><strong className="text-[var(--text)]">Conversations:</strong> Chat messages between you and your agent are stored locally on your device. Cloud-synced conversations (paid tiers) are encrypted at rest on our servers</li>
              <li><strong className="text-[var(--text)]">Memory data:</strong> Facts, preferences, and knowledge your agent accumulates — stored locally, with optional cloud sync</li>
              <li><strong className="text-[var(--text)]">Usage data:</strong> Feature usage patterns, session duration, model selections</li>
            </ul>

            <h3 className="font-semibold text-[var(--text)] mb-2">c) Automatically Collected Information</h3>
            <ul className="list-disc pl-6 space-y-1">
              <li>Device information (OS version, app version, hardware model)</li>
              <li>IP address (for security and abuse prevention)</li>
              <li>Crash reports and error logs (no conversation content included)</li>
              <li>Anonymous analytics (see Section 6)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">2. How We Use Your Information</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>To provide, maintain, and improve the Service</li>
              <li>To process payments and manage subscriptions</li>
              <li>To communicate with you about your account, updates, and support</li>
              <li>To detect and prevent fraud, abuse, and security threats</li>
              <li>To analyze usage patterns to improve user experience (anonymous, aggregate only)</li>
              <li>To comply with legal obligations</li>
            </ul>
            <p className="mt-3"><strong className="text-[var(--text)]">We do not use your conversations or memory data to train AI models.</strong></p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">3. Data Storage</h2>

            <div className="space-y-4">
              <div className="p-4 rounded-lg bg-[var(--surface)] border border-[var(--border)]">
                <h3 className="font-semibold text-[var(--text)] mb-1">Local Storage (Your Device)</h3>
                <p>Conversations, memories, knowledge graph data, and API keys are stored on your local machine. This data is under your direct control. You can delete it at any time by clearing application data or uninstalling the app.</p>
              </div>
              <div className="p-4 rounded-lg bg-[var(--surface)] border border-[var(--border)]">
                <h3 className="font-semibold text-[var(--text)] mb-1">Cloud Storage (Our Servers)</h3>
                <p>Account data, subscription information, and cloud-synced conversations (for paid tiers) are stored on DigitalOcean infrastructure located in Canada (Toronto data center). All data is encrypted in transit (TLS 1.3) and at rest (AES-256).</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">4. Third-Party Services</h2>
            <p className="mb-3">We integrate with the following third-party services:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong className="text-[var(--text)]">Ollama Cloud / AI Providers:</strong> When you use AI models through Lodestone, your messages are sent to the provider you selected (OpenAI, Anthropic, Groq, Ollama Cloud, or your own endpoint). Each provider has their own privacy policy. We do not log or store the content of API requests beyond what is needed for delivery.</li>
              <li><strong className="text-[var(--text)]">Stripe:</strong> Payment processing. Stripe handles your credit card information directly — we never see or store your full card number. <a href="https://stripe.com/privacy" className="text-[var(--cyan)]">Stripe's Privacy Policy</a></li>
            </ul>
            <p className="mt-3">We do not sell your data to third parties. We do not share your personal information with third parties except as described in this policy or as required by law.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">5. Data Security</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>All network traffic encrypted via TLS 1.3</li>
              <li>Data at rest encrypted with AES-256</li>
              <li>API keys stored locally on your device only</li>
              <li>Regular security audits and vulnerability assessments</li>
              <li>Access controls limiting employee access to user data</li>
              <li>Incident response plan for data breaches</li>
            </ul>
            <p className="mt-3">While we take reasonable measures to protect your data, no system is perfectly secure. We encourage you to use strong passwords and enable two-factor authentication when available.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">6. Cookies and Analytics</h2>
            <p className="mb-3">We use minimal, privacy-respecting analytics:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong className="text-[var(--text)]">Essential cookies:</strong> Session authentication (required for login)</li>
              <li><strong className="text-[var(--text)]">Analytics:</strong> We collect anonymous, aggregate usage statistics (page views, feature usage, error rates). No personally identifiable information is collected through analytics</li>
              <li><strong className="text-[var(--text)]">No tracking:</strong> We do not use cross-site tracking, advertising pixels, or sell analytics data</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">7. Data Retention and Deletion</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong className="text-[var(--text)]">Active accounts:</strong> Data retained for the duration of your account</li>
              <li><strong className="text-[var(--text)]">Closed accounts:</strong> All cloud data deleted within 30 days of account closure</li>
              <li><strong className="text-[var(--text)]">Local data:</strong> Remains on your device until you delete it. Uninstalling the app removes all local data</li>
              <li><strong className="text-[var(--text)]">Backup data:</strong> Deleted from backups within 90 days</li>
              <li><strong className="text-[var(--text)]">Anonymous analytics:</strong> Retained in aggregate form indefinitely (not identifiable to you)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">8. Your Rights</h2>
            <p className="mb-3">Under PIPEDA and applicable Canadian privacy law, you have the right to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong className="text-[var(--text)]">Access:</strong> Request a copy of all personal data we hold about you</li>
              <li><strong className="text-[var(--text)]">Correction:</strong> Request correction of inaccurate personal data</li>
              <li><strong className="text-[var(--text)]">Deletion:</strong> Request deletion of your personal data and account</li>
              <li><strong className="text-[var(--text)]">Withdrawal of consent:</strong> Withdraw consent for data processing (may affect Service functionality)</li>
              <li><strong className="text-[var(--text)]">Complaint:</strong> File a complaint with the Office of the Privacy Commissioner of Canada</li>
            </ul>
            <p className="mt-3">To exercise any of these rights, contact us at <a href="mailto:privacy@heylodestone.com" className="text-[var(--cyan)]">privacy@heylodestone.com</a>. We will respond within 30 days.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">9. Children's Privacy</h2>
            <p>Lodestone is not directed to children under 13. We do not knowingly collect personal information from children under 13. If we become aware that we have collected data from a child under 13, we will delete it promptly.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">10. International Data Transfers</h2>
            <p>Your data is stored in Canada. If you access the Service from outside Canada, your data may be transferred to, processed in, and stored in Canada. By using the Service, you consent to this transfer.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">11. Changes to This Policy</h2>
            <p>We may update this Privacy Policy from time to time. Material changes will be notified via email or in-Service notice at least 30 days before taking effect. Continued use after changes become effective constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-3">12. Contact</h2>
            <p>For privacy inquiries, contact our Privacy Officer at <a href="mailto:privacy@heylodestone.com" className="text-[var(--cyan)]">privacy@heylodestone.com</a>.</p>
            <p className="mt-2">Greyrock Studio<br/>Ottawa, Ontario, Canada</p>
          </section>

          <section className="pt-4 border-t border-[var(--border)]">
            <p className="text-sm">Office of the Privacy Commissioner of Canada: <a href="https://www.priv.gc.ca" className="text-[var(--cyan)]">priv.gc.ca</a></p>
          </section>
        </div>

        <div className="mt-12 flex gap-6 justify-center text-sm">
          <Link to="/terms" className="text-[var(--text-muted)] hover:text-[var(--text)] no-underline transition-colors">Terms of Service</Link>
          <Link to="/eula" className="text-[var(--text-muted)] hover:text-[var(--text)] no-underline transition-colors">EULA</Link>
          <Link to="/" className="text-[var(--text-muted)] hover:text-[var(--text)] no-underline transition-colors">← Home</Link>
        </div>
      </div>
    </div>
  )
}
